### ISSUE TITLE
Release 0.0.3

### ISSUE THREAD

**Issue by smondet** [hammerlab/genspio#107]
- [x] finish move to base+fmt (`examples/`)
- [ ] redeploy and test multi-git and cosc
- [x] remove mentions of nonstd and sosa, check mentions of base and fmt

**Comment by smondet** [comment]
https://smondet.gitlab.io/genspio-doc/ built properly, and test succeeded with current `master`

**Comment by NathanReb** [comment]
Is the list still up to date and will you have time to work on this soon? A release would greatly help us as it would allow `genspio` users to work with [opam-monorepo](https://github.com/ocamllabs/opam-monorepo).

Is there something we can offer our help with?

The alternative for us is to work on a dune port of 0.0.2 on [dune-universe/opam-overlays](https://github.com/dune-universe/opam-overlays) which would require us to in turn also port `sosa` and `nonstd`. That obviously isn't my prefered outcome so I'm happy to instead help with getting a fresh release of `genspio`!

**Comment by smondet** [comment]
OK WIP https://github.com/ocaml/opam-repository/pull/20238

(and thanks for the heads-up :) )

**Comment by smondet** [comment]
Release done :tada:

**Comment by NathanReb** [comment]
Awesome, thanks!
